### PR TITLE
Create styled-components primitives example

### PR DESCRIPTION
**Pull request by macintoshhelper**
Create `styled-components` examples using the `react-primitives` package for cross-platform components.

~(probably worth waiting for my `react-primitives` PR to be merged first, to avoid needing to use a fork).~

~(prettier fails on CI, but is passing locally, strange)~
 
~And **please don't merge before** the `webpack-config` PR is merged.~

Ready to merge now.

**Related issues**
> #194

### CODE REVIEW

**Comment by ilyalesik** [comment]
So, should we wait for [react-primitives PR](https://github.com/lelandrichardson/react-primitives/pull/143) will be merged?

**Comment by macintoshhelper** [comment]
The PR has been merged & published, so good to merge/publish this PR now. I've removed the fork aliasing, and added a `clean`/`build` npm script, and a screenshot for the `README` 🙂

**Comment by ilyalesik** [comment]
That's really great, thanks!

@all-contributors please add @macintoshhelper  for code

@macintoshhelper what are you think, should we move `styled` helper to main package later (make it as a part of `react-figma` API)?

**Comment by macintoshhelper** [comment]
Thanks! I think it makes sense to leave the `styled` helper out of the core package, it would commit the library to supporting `styled-components` as part of the API, and I think it makes sense to not push for one styling library specifically, and it effectively functions as an alias for `styled-components/primitives`, makes sense for people to use that instead. Worth adding a `styled-components` section to the docs though. I don't believe much documentation exists around `styled-components/primitives`, just a blog post.

`styled-components/primitives` works fine for web without my helper, but `react-primitive`'s `<View>` component uses `react-native-web`, which I've found breaks `styled-components` SSR support, and conflicts with some of the styling implementation.

**Pull request merged**
