### PR TITLE
Implemented blendMixin, closes: #27

### PR DESCRIPTION
**Pull request by HVish**

### CODE REVIEW

**Comment by ilyalesik** [comment]
Hi, @HVish! Thank you for the PR! 
I guess, only CSS-like properties can be supported inside `style` tag. So, I propose removing `isMask `, `effects` and `effectStyleId ` from `transformBlendProperties `. Also, mapping from [CSS blend-mode](https://www.w3schools.com/cssref/pr_mix-blend-mode.asp) to Figma `type BlendMode` needed. E.g. `"color-dodge"` -> `"COLOR_DODGE"`

**Comment by HVish** [comment]
@ilyalesik  I could not map following blend modes, since these modes does not exist in CSS.
- PASS_THROUGH
- LINEAR_BURN
- LINEAR_DODGE

I took reference from [MDN's mix-blend-mode documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode).

Can you help me with those missing blend modes?

**Comment by ilyalesik** [comment]
I think we can just ignore these modes. And transform only CSS blend modes.

**Comment by HVish** [comment]
Ok then, I have done it at my end. You can check this [commit](https://github.com/react-figma/react-figma/pull/71/commits/6fe1d0419f4d04f156212cea28f6164f0c1ca6d5).

**Comment by ilyalesik** [comment]
Awesome! Thanks!

**Pull request merged**
